### ISSUE TITLE
Not on DUB

### ISSUE THREAD

**Issue by MatthewFrench** [Dgame/Dgame#22]
Pretty important feature that would make this way more popular. (and easier to setup)

**Comment by Extrawurst** [comment]
a lincense is missing too AFAIK

**Comment by Dgame** [comment]
License: http://rswhite.de/dgame4/?page=license

Yes it should be on DUB, but  before it should be adapted for 2.067. But I have no time until end of march.

**Comment by kingsleyh** [comment]
please please please put this on dub - or at least make it so that it can use dub after cloning the repo. Also the install instructions still point to the derelict3 github site which says it's no longer maintained and doesn't compile with the latest dmd compiler. Instead you have to go to the new derelict site where it has been broken into multiple libs. For a D noob like me - I need more instructions. 

Also I'm on osx - so I could test out stuff on osx if you need that. (Once I figure out how to get everything installed so that I can run a sample app that is :) :) )

**Comment by Dgame** [comment]
I will try to update Dgame this weekend and also I will try to adapt the Derelict stuff. ;) But putting Dgame on DUB will take some more time since I have no experience with DUB and I have currently my exams.

**Comment by Dgame** [comment]
Thanks to @growlercab Dgame is adapted for DUB usage. I will register Dgame on DUB until evening.
